name: CI
on: [ push ]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
      - name: Install .NET EF Tools
        run: dotnet tool install --global dotnet-ef
      - name: Update Database
        run: dotnet ef database update --project ./src/Optivem.Kata.Banking.Infrastructure
      - name: Run Build
        run: dotnet build
      - name: Run Tests
        run: dotnet test